-- AUTO-GENERATED IMPORTS
-- This section is automatically generated by scripts/sync_modules.py
import UFRF.Addressing
import UFRF.Adele
import UFRF.AngularEmbedding
import UFRF.AxiomAudit
import UFRF.Axiomatics
import UFRF.BreathingCycle
import UFRF.Calculus
import UFRF.Constants
import UFRF.DivisionAlgebras
import UFRF.FineStructure
import UFRF.Foundation
import UFRF.Fourier
import UFRF.GoldenAngle
import UFRF.InverseLimit
import UFRF.KeplerTriangle
import UFRF.KernelProof
import UFRF.KissingEigen
import UFRF.Manifold
import UFRF.Noether
import UFRF.NumberBases
import UFRF.PRISMAlgebra
import UFRF.Padic
import UFRF.PhaseSpaceCartography
import UFRF.Phenomena
import UFRF.PositionalPhase
import UFRF.PrimeChoreography
import UFRF.Projections
import UFRF.Recursion
import UFRF.Simplex
import UFRF.StarPolygon
import UFRF.Structure13
import UFRF.ThreeLOG
import UFRF.Trinity
import UFRF.Waveform

/-!
# Universal Field Resonance Framework — Lean 4 Formalization

## The Single Axiom
Everything derives from the Trinity: `{-½, 0, +½}` with sum = 0.

## Module Index

| Module | Content | Key Result |
|--------|---------|------------|
| Simplex | 3-simplex face counting | `simplex3_face_count` |
| KeplerTriangle | REST amplitude derivation | `kepler_pythagorean` |
| Structure13 | Projective uniqueness of 13 | `uniqueness_of_thirteen` |
| Foundation | Derives cycle length from Trinity | `cycle_is_thirteen` |
| Constants | φ, π, τ, peak amplitude | `peak_is_two` |
| Trinity | Axiom 1, conservation, uniqueness | `trinity_uniqueness` |
| ThreeLOG | Tensor grades, 9 interior positions | `nine_interior_positions` |
| BreathingCycle | ZMod 13 ring, PRISM operators | `bridge_seed_wraps` |
| AngularEmbedding | S¹ mapping, Rod-Staff cross | `observer_is_orthogonal` |
| Addressing | (ℤ, ZMod 13) coordinate system | `phase_count` |
| Manifold | Torus T² + ZMod bridge | `torus_bin_spacing` |
| Recursion | Scale invariance, completeness | `no_first_step` |
| DivisionAlgebras | Hurwitz, 15 dimensions | `visible_dimension_count` |
| NumberBases | Base 10/12/13 (derived) | `base13_is_full_cycle` |
| FineStructure | α⁻¹ = 4π³ + π² + π | `alpha_inv_floor_137` |
| Waveform | Piecewise breathing shape | `seed_expansion_match` |
| PrimeChoreography | Prime superposition | `prime_phase_residues` |
| GoldenAngle | Golden Angle → Position 5 | `golden_angle_bins_to_5` |
| Projections | Manifold collapse operators | `three_projections_span` |
| Noether | Gauge groups, conservation | `total_gauge_bosons` |
| Calculus | Differentiation, scale descent | `ftc_scale_roundtrip` |
| Phenomena | Physical constants at phases | `alpha_inv_decomposition` |
| PRISMAlgebra | Primitive roots, scale projection | `two_pow_12_is_one` |
| KernelProof | Single proof certificate | (collects all key results) |
| Padic | Universal prime tower | `universal_conservation` |
| Adele | Adelic product ring | `adele_conservation` |
| StarPolygon | Prime visit orders on ℤ/13ℤ | `visit_order_5` |
| PositionalPhase | Position-based phase, golden emergence | `golden_angle_emergence` |
| KissingEigen | K(3)=12 eigenstructure | `kissing_plus_center_is_cycle` |
| Fourier | Character theory / DFT on ℤ/13ℤ | `fourier_basis_exists` |
| AxiomAudit | `#print axioms` for 53 key theorems | (axiom dependency certificate) |
-/
