#!/usr/bin/env python3
import os
import glob
import re

def main():
    ufrf_dir = "UFRF"
    root_file = "UFRF.lean"
    
    # We only want files that end exactly in .lean, so we skip .removed, .bak, etc.
    lean_files = sorted(glob.glob(f"{ufrf_dir}/*.lean"))
    
    imports = []
    for file in lean_files:
        basename = os.path.basename(file)
        if basename.endswith(".lean"):
            module_name = basename[:-5]
            imports.append(f"import UFRF.{module_name}")
    
    # Read existing content to extract docstring
    docstring = ""
    if os.path.exists(root_file):
        with open(root_file, "r") as f:
            content = f.read()
            # Match lean markdown comment block
            match = re.search(r'/-!.*?-/', content, re.DOTALL)
            if match:
                docstring = match.group(0)
    
    if not docstring:
        docstring = """/-!
# Universal Field Resonance Framework — Lean 4 Formalization

## The Single Axiom
Everything derives from the Trinity: `{-½, 0, +½}` with sum = 0.
-/"""

    header = f"-- AUTO-GENERATED IMPORTS\n-- This section is automatically generated by scripts/sync_modules.py\n"
    new_content = header + "\n".join(imports) + "\n\n" + docstring + "\n"
    
    with open(root_file, "w") as f:
        f.write(new_content)
        
    print(f"✅ Generated {root_file} with {len(imports)} module imports.")

if __name__ == "__main__":
    main()
